package com.hjw.wst.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * NFixcardId generated by MyEclipse - Hibernate Tools
 */

@Entity
@Table(name = "WEB_ROLEREPORT")
public class WebRoleReport implements java.io.Serializable {
	 private static final long serialVersionUID = -97502163798576023L;
	 @Id
	    @GeneratedValue(generator = "paymentableGenerator")
	    @GenericGenerator(name = "paymentableGenerator", strategy = "uuid")
	    @Column(name = "id", unique = true, nullable = false,length = 50)
	private String id;

		@Column(name = "role_id")
	private String role_id;

		@Column(name = "rolemenu_id")
	private int rolemenu_id;

		@Column(name = "remark")
	private String remark;


	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}


	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getRole_id() {
		return role_id;
	}

	public void setRole_id(String role_id) {
		this.role_id = role_id;
	}

	public int getRolemenu_id() {
		return rolemenu_id;
	}

	public void setRolemenu_id(int rolemenu_id) {
		this.rolemenu_id = rolemenu_id;
	}
	
}