package com.hjw.wst.domain;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * NFixcardId generated by MyEclipse - Hibernate Tools
 */
@Entity
@Table(name = "Web_Role")
public class WebRole implements java.io.Serializable {
	private static final long serialVersionUID = -97502163798576023L;
	
	 @Id
	 @GeneratedValue(generator = "paymentableGenerator")
	 @GenericGenerator(name = "paymentableGenerator", strategy = "uuid")
	 @Column(name = "id", unique = true, nullable = false,length = 50)
	private String id;

	@Column(name = "rolename")
	private String rolename;

	@Column(name = "remark")
	private String remark;

	@Column(name = "datetime")
	private String datetime;
	
	@Column(name = "ry")
	private String ry;
	
	@Column(name = "apptype")
	private String apptype;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getRolename() {
		return rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getDatetime() {
		return datetime;
	}

	public void setDatetime(String datetime) {
		this.datetime = datetime;
	}

	public String getRy() {
		return ry;
	}

	public void setRy(String ry) {
		this.ry = ry;
	}

	public String getApptype() {
		return apptype;
	}

	public void setApptype(String apptype) {
		this.apptype = apptype;
	}
	
	
}