package com.hjw.wst.model;

/**
 * NFixcardId generated by MyEclipse - Hibernate Tools
 */

public class RoleModel implements java.io.Serializable {
	private static final long serialVersionUID = -97502163798576023L;
	// Fields
	private String id;
	private String rolename;
	private String remark;
	private String datetime;
	private String ry;
	private String gwbm;
	private String gwmc;
	private String bmbh;
	private String gwjsid;
	private String rolegnid;
	private String roleshid;
	private String rolezyid;
	private String reportids;
	
	private String center;
	
	public String getCenter() {
		return center;
	}

	public void setCenter(String center) {
		this.center = center;
	}

	public String getReportids() {
		return reportids;
	}

	public void setReportids(String reportids) {
		this.reportids = reportids;
	}

	private String userDepId;

	public String getGwbm() {
		return gwbm;
	}

	public void setGwbm(String gwbm) {
		this.gwbm = gwbm;
	}

	public String getGwmc() {
		return gwmc;
	}

	public void setGwmc(String gwmc) {
		this.gwmc = gwmc;
	}

	public String getBmbh() {
		return bmbh;
	}

	public void setBmbh(String bmbh) {
		this.bmbh = bmbh;
	}

	public String getGwjsid() {
		return gwjsid;
	}

	public void setGwjsid(String gwjsid) {
		this.gwjsid = gwjsid;
	}

	public String getRoleshid() {
		return roleshid;
	}

	public void setRoleshid(String roleshid) {
		this.roleshid = roleshid;
	}

	public String getRolezyid() {
		return rolezyid;
	}

	public void setRolezyid(String rolezyid) {
		this.rolezyid = rolezyid;
	}

	public String getRolename() {
		return rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getDatetime() {
		return datetime;
	}

	public void setDatetime(String datetime) {
		this.datetime = datetime;
	}

	public String getRy() {
		return ry;
	}

	public void setRy(String ry) {
		this.ry = ry;
	}

	public String getRolegnid() {
		return rolegnid;
	}

	public void setRolegnid(String rolegnid) {
		this.rolegnid = rolegnid;
	}

	public String getUserDepId() {
		return userDepId;
	}

	public void setUserDepId(String userDepId) {
		this.userDepId = userDepId;
	}
}