USE [peis_tt_190117]
GO
/****** Object:  Table [dbo].[center_configuration]    Script Date: 03/15/2019 09:13:52 ******/
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'ADD_ITEM_SEARCH_TYPE', N'0', N'Y', N'鍔犻」鏃舵ā绯婃悳绱㈡柟寮忥紝0琛ㄧず鍙彸妯＄硦锛?琛ㄧず宸﹀彸妯＄硦鏌ヨ')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'BAR_CODE_URL', N'D:\barcodeService\HjwGuidBarService.exe', N'Y', N'调用打印条码.EXE文件路径')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'BARCODE_PRINT_TYPE', N'2', N'Y', N'导检单和条码打印服务程序，1表示调用只支持IE的打印程序（旧打印程序），
2表示调用支持火狐、IE的打印服务（新打印程序）')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'体检中心', N'CARD_INFO_PREFIX', N'1', N'Y', N'会员卡号前缀生成规则 1表示无前缀、2表示数据字典卡类型remark配置前缀加年月日')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'CARD_READER_INFO', N'd009', N'Y', N'会员卡读卡器对应设备编号')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'体检中心', N'COLLECT_FEES_WHOLE', N'1', N'Y', N'收费处凑整可使用最大金额')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'DEFAULT_ADDRESS', N'', N'Y', N'默认地址配置')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'DEP_ORDER_TYPE', N'2', N'Y', N'首页科室排序方式:1,名称2,序号')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'DJD_CODE_URL', N'D:\barcodeService\HjwGuidBarService.exe', N'Y', N'调用打印导检单.EXE文件路径')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'DJT_ADD_DEP', N'131,21,17', N'Y', N'需要显示的统计科室，id以逗号隔开  例如 :131,21')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'DJT_ADD_TIEM_TYPE', N'0', N'Y', N'登记台加项页面模式0表示传统1表示按钮加项')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'DJT_HIDE_DEPT_ITEM', N'246', N'Y', N'登记台加项隐藏哪些科室下的项目，逗号隔开科室id')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'EXAM_END_ITEM_SEQ', N'', N'Y', N'结束回收页面未检收费项目列表，配置默认排在前边的收费项目.配置收费项目ID，以 , 隔开')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'EXAM_END_SHOW_ITEMID', N'', N'Y', N'结束回收页面显示配置的检查项目名称和结果，配置检查项目ID，以 , 隔开')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'EXAM_RESULT_SHOW_ITEMID', N'', N'Y', N'总检结论始终汇总的检验科项目ID，多个项目以逗号隔开。例：1,2,3')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'EXAM_RESULT_STYLE', N'4', N'Y', N'总检结论汇总样式, 1 普通样式、2 浙医二样式、3 江苏省级机关医院 、4西苑医院')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'EXAM_SUMMARY_CHECK_DEFAULT', N'1', N'Y', N'总检室首页查询条件默认勾选。1 表示勾选体检号，2 表示勾选体检日期')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'EXAM_SUMMARY_DEFAULT_DISEASEIDS', N'', N'Y', N'总检室没有匹配到疾病，默认显示的疾病id配置，多个疾病ID以,隔开')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'解放军180医院体检中心', N'EXAM_SUMMARY_FINAL_NUM', N'5', N'Y', N'总检医生一次获取可总检人员个数')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'EXAM_SUMMARY_PACS_URL', N'', N'Y', N'总检页面PACS阅片按钮的地址配置（注：配置了地址才会显示该按钮）')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'体检中心', N'EXAM_SUMMARY_STYLE', N'2', N'Y', N'总检室总监模式，1 普通总检模式，2 180总检模式')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'EXAMSTATUS_UP', N'http://localhost/putExaminfostatus.action', N'Y', N'上传体检状态给第三方系统')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'EXAMSUMMARY_RESULT_IN', N'减退,糜烂', N'Y', N'总检结论汇总，普通和影像科室结论包含配置内容，汇总到总检总论里（注：只需要关注结论中存在正常、未见、阴性字样的结论）')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'FEES_MX_POINT', N'1', N'Y', N'收费处打印收费明细单，1表示传体检号，2表示传结算单号')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'体检中心', N'HEALTH_GET_DEP', N'123,345', N'Y', N'拥有健康管理项目的部门，以小写的逗号隔开')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'体检中心', N'HEALTH_GET_IS', N'Y', N'Y', N' 是否在打印室整单时候判断健康管理报告')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'HIS_FEE_TYPE', N'1', N'Y', N'his收费申请类型：1，不关联价表')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'INVOICE_PRINT_TYPE', N'2', N'Y', N'发票打印方法，1 表示帆软打印，2表示客户端打印')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_ACCEPTANCECHECK', N'Y', N'Y', N'是否启用核收功能')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_ADD_GSETEXAMTYPE', N'7,8', N'Y', N'00')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_ADD_SETEXAMTYPE', N'N', N'Y', N'增加套餐是否按照套餐类型区分')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_ADD_TSETEXAMTYPE', N'7,8', N'Y', N'团体增加套餐对应套餐类型id，用逗号隔开')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_AFTER_PAY', N'N', N'Y', N'系统配置是否后付费，Y表示后付费，N表示先付费')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_ALL_DEPT_ITEM', N'Y', N'Y', N'细项是否为 全科室下Y  该科室下N')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_APPLY_UPDATE', N'Y', N'Y', N'审核医生是否能修改总检信息')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_APPOINTMENT_DATE', N'N', N'Y', N'是否需要输入预约日期(登记台页面)')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_AUTOMATIC_CASHIER_DAILY', N'Y', N'Y', N'收费处是否启用自动收费员日结功能')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_BAOBIAO_TREE', N'N', N'Y', N'报表功能是否采用树形菜单')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_BAODAO_HIS_APPLICATION', N'N', N'Y', N'团体报到、个人添加项目是否自动发送HIS缴费申请')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_BAODAODA_CHECKEBOX', N'Y', N'Y', N'登记台首页 报到打：（导简单，条码，档案号）复选框  Y默认勾选，N不勾选')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_BATCH_CHECK', N'1', N'Y', N'是否体检任务自动审核(0:否;1:是)')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_BATCH_EXAMINE', N'Y', N'Y', N'终检室批量审核按钮，Y显示按钮，N不显示')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_CHANGE_CHARGING_ITEM', N'Y', N'Y', N'通过项目和样本关系维护带出项目 （N：不带出，Y:带出）')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_CHANGE_SET_PRICE', N'Y', N'Y', N'收费项目价格变动时是否联动修改套餐价格')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_CHARGINGWAY_ZERO', N'Y', N'Y', N'收费处选中的收费方式金额为0时,该收费方式是否写入数据库')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_CHECK_SENSITIVE_WORD', N'N', N'Y', N'普通科室是否启用敏感词校验')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_COMMON_ITEM_CHANGE', N'N', N'Y', N'普通科室检查项目是否按收费项目切换')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_COMPANY_SHOW_POW', N'N', N'Y', N'单位查询是否关联创建人')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_CONTRACT_CHECK', N'1', N'Y', N'是否方案审核时，一并审核合同(0:否;1:是)')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_CONTRACT_EXADATE', N'180', N'Y', N'默认合同有效期天数')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_CONTRACT_NO', N'TJZXHT', N'Y', N'合同编号前面部分')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXX', N'IS_CUSTOM_IDENTIFICATION', N'4', N'Y', N'定义哪些人员类别的体检者需要在页面有加重标识提醒')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXX', N'IS_CUSTOMER_DW_NAME_TYPE', N'N', N'Y', N'姓名定位是否采用精确查询：Y精确；N模糊')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_DAH_INTERFACE', N'N', N'Y', N'是否执行档案号接口')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_DAH_INTERFACE_SHENCHENG', N'N', N'Y', N'接口获取不到档案号,咱们系统自动生成档案号  Y生成  N不生成')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXX', N'IS_DEFAULT_TEN', N'Y', N'Y', N'登记台加项是否默认为10折 默认10折：Y，自动计算折扣：N')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_DEP_DISEASE', N'Y', N'Y', N'是否启用科室检查重大阳性发现功能')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_DEP_EDIT_QUESTIONNAIRE', N'Y', N'Y', N'是否启用普通科室检查页面具有修改问卷内容的功能')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_DEPARTINSPECT_SUMMARY_EDIT', N'Y', N'Y', N'普通科室结论小结是否允许修改')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_DEPINSPECT_CHECKED', N'Y', N'Y', N'普通科室项目已检查是否给出提示')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_DEPINSPECT_WORD', N'N', N'Y', N'普通科室检查双击弹出页是否显示所有项目结果词。N显示不常用的，Y显示所有的')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_DEPITEM_SAVE', N'Y', N'Y', N'普通科室检查未录入结果，结果表是否保存该体检项目信息')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_DEPRESULT_SHOW', N'未见异常', N'Y', N'科室结论默认显示词')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_DEPT_TYPE', N'BJTT', N'Y', N'普通科室检查样式：COMM表示普通、XYYY表示西苑医院')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_DISEASE_KNOW_TYPE', N'2', N'Y', N'1表示疾病知识库上可以维护关系，2表示取消疾病知识库关系维护')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_DISEASE_LOGIC_DEP', N'N', N'Y', N'总检疾病逻辑判断是否关联科室')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_DISEASE_MERGE', N'N', N'Y', N'总检室疾病合并是否需要继续选择疾病,N不需要、Y需要')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_DISEASE_SHOW', N'N', N'Y', N'总检页面是否显示疾病发现')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_DJD_AUTO_RECOVER', N'Y', N'Y', N'导检单是否自动回收 是Y 否N')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_DJT_EXAMINFO_NO_SUMMARY', N'N', N'Y', N'登记台是否判断上次体检未总检时不让新增体检')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_DJT_HIDE_DEPT_ITEM', N'N', N'Y', N'是否开启登记台加项隐藏部分科室下的项目')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'xxxxxx', N'IS_DJT_SHOW_WENJUAN', N'N', N'Y', N'登记台是否显示问卷结果页面，Y,显示N,不显示')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_DJT_TYPE', N'COMM', N'Y', N'登记台样式COMM表示普通、DBGJ东北国际 ZJTY浙江二院')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_END_EXAM', N'N', N'Y', N'是否结束总检 就补做登记 Y结束总检 N无需总检 ')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_EXAM_DISEASE_ITEM', N'N', N'Y', N'总检室汇总的阳性是否添加项目与结果(注：只有启用关联科室逻辑，本功能才会有效)')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_EXAM_DISEASE_SEQ', N'N', N'Y', N'总检疾病逻辑是否按科室排序')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'体检中心', N'IS_EXAM_RESULT_CANFINAL', N'Y', N'Y', N'180总检模式获取总检 N表示只获取整单上传的人员，Y表示可以获取整单上传的人以及全部检查项目已检查的人员')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'体检中心', N'IS_EXAM_RESULT_CITEM', N'N', N'Y', N'查询检验科结果是否关联收费项目ID')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXX', N'IS_EXAM_RESULT_DETAIL_CHARGINGID', N'Y', N'Y', N'检验结果是否关联收费项目查询')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_EXAM_SUGGEST', N'N', N'Y', N'总检室阳性发现列表是否自动给建议添加阳性名称')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_EXAM_SUMARRY_EDIT', N'Y', N'Y', N'总检结论是否可以修改')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_EXAM_SUMARRY_NEW', N'N', N'Y', N'已总检完成,总检结论是否汇总最新的')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_EXAM_SUMMARY', N'Y', N'Y', N'结论是否汇总全部结果')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_EXAM_ZHEER_GETBAOGAO', N'http://192.168.1.103:8080/getCardIdPDF.action', N'Y', N'获取评测卡健康问卷报告')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_EXAM_ZHEER_SHOWBAOGAO', N'Y', N'Y', N'科室是否显示获取评测报告按钮:Y显示评测报告按钮,N不显示')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_EXAMDEP_APPROVER', N'N', N'Y', N'普通科室检查，是否启用审核功能')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_EXAMRESULTDETAIL_DOCTORPAGE_SHOW', N'N', N'Y', N'检验科结果保存是否需要选择审核医生')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_EXAMSET_COMPANY', N'N', N'Y', N'套餐是否按单位过滤')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'体检中心', N'IS_EXAMSUMMARY_DISEASE_DEP_LOGIC', N'N', N'Y', N'总检室普通科室疾病逻辑判断是否启用普通科室小结逻辑（只支持IS_DISEASE_LOGIC_DEP 为N的模式）')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_EXAMSUMMARY_NEWDISEASEPAGE_SHOW', N'Y', N'Y', N'总检室新增疾病是否弹出页面')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_FEES_BAODAO', N'Y', N'Y', N'收费处是否启用预约人员报道功能')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_FEES_MX_POINT_CHECKED', N'N', N'Y', N'收费处打印收费明细单复选框收费选中，N不选中，Y选中')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_FEES_QIJIAN', N'N', N'Y', N'收费处收费是否包含弃检项目')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXX', N'IS_GBAODAO_QUEUE_SEND', N'N', N'Y', N'个检报道是否发送排队申请')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_GCUSTOM_GH', N'N', N'Y', N'登记台个人新增和修改人员时是否做挂号操作')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_GENERATE_CONCLUSION', N'Y', N'Y', N'是否自动生成结论（一般科室检查）')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_GROUP_USERED_EDIT', N'Y', N'Y', N'ddd')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_HANSIDJD_TYPE', N'0', N'Y', N'是否采用翰思模式打印导检单(0 表示否，1表示是)')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_HANSIDJD_URL', N'http://www.huojianwa.com/web', N'Y', N'翰思导检单二维码地址')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXX', N'IS_HAVE_MAX_AMOUNT', N'N', N'Y', N'团体登记页面是否有最大金额限制（此功能用于DJT_ADD_TIEM_TYPE为3的页面 Y 是 N 否）')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_HG_WRITEJIUZHENKA', N'N', N'Y', N'调用HIS 接口 绑定卡信息， Y开启，N关闭')
GO
print 'Processed 100 total records'
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_HIS_DOCTOR_ID', N'00223', N'Y', N'his开单医生id')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_HIS_DOCTOR_NAME', N'8888', N'Y', N'his开单医生姓名')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_HIS_INTERFACE', N'N', N'Y', N'是否启用HIS接口')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_HIS_LIS_CHECK', N'N', N'Y', N'Y：lis申请前先付费，N后付费')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_HIS_PACS_CHECK', N'Y', N'Y', N'Y：PACS申请前先付费，N后付费')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_HISNUM_REPEAT', N'Y', N'Y', N'是否允许his关联码重复')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_ITEM_HC', N'N', N'Y', N'收费项目带出耗材项目  Y带出   N不带出')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_JIUZHENKA_DUKAQI', N'J001', N'Y', N'灏辫瘖鍗¤鍗″櫒  J001榛勫唸灏辫瘖鍗¤鍗″櫒')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_LIS_BANDING', N'N', N'Y', N'是否绑管')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_LIS_BANGDING', N'N', N'Y', N'是否绑管')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_LIS_CJFS', N'47', N'Y', N'采集方式id（中联使用）')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_LIS_DEPT_ID', N'799', N'Y', N'lis开单科室id')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_LIS_DEPT_NAME', N'体检科', N'Y', N'lis开单科室名称')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_LIS_INTERFACE', N'Y', N'Y', N'是否启用LIS接口')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXX', N'IS_LIS_INTERFACE_TYPE', N'3', N'Y', N'1表示按照申请单号发送申请，2表示按照一次体检发生申请，写第三方申请号,3表示按照一次体检发送申请，不写已经采样状态')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_LIS_PACS_DOCTOR_ID', N'tj', N'Y', N'lis PACS开单医生id')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_LIS_PACS_DOCTOR_NAME', N'体检', N'Y', N'lis pacs开单医生姓名')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_LIS_ZXKS_ID', N'146', N'Y', N'执行科室id（中联使用）')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_MEDICAL_INSURANCE_CARD', N'N', N'Y', N'是否启用医保卡')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_MEMBERSHIP_CARD', N'N', N'Y', N'是否启用会员卡')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_NEED_NEW_EXAMNUM', N'N', N'Y', N'补做体检号生成规则：N表示用在原来体检号增加B，Y表示重新生成体检号')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_NEED_SHOW_ABANDON', N'Y', N'Y', N'登记台补做是否显示弃检的项目 Y显示 N不显示')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXX', N'IS_NEEDALERT_WJITEM', N'', N'Y', N'整单室缺项目时不弹出配置科室ID下的所有项目,ID 以,号隔开 12,23,24')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_OWN_URL', N'http://192.168.0.110:8080', N'Y', N'翰思报表，设置网站url地址')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_PACS_CUSINFO_UP', N'N', N'Y', N'是否启用pacs档案信息同步接口')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_PACS_INTERFACE', N'Y', N'Y', N'是否启用PACS接口')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_PLAN_ENDTIME', N'17:20', N'Y', N'体检结束时间')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_PLAN_STARTTIME', N'09:00', N'Y', N'体检开始时间')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'体检中心', N'IS_PRINT_BARCODE_ITEM_PAY', N'N', N'Y', N'登记台打印条码是否判断项目是否付费，N表示不用判断，Y表示需要判断项目已收费')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_PRIVE_DAY', N'1', N'Y', N'价表改变，字典提示天数')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_QUEUE_CHECK', N'N', N'Y', N'是否发送排队申请')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXX', N'IS_REPORT_ROOM', N'N', N'Y', N'是否需要报告室流程，Y需要,N不需要')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_REPORT_UPLOAD', N'N', N'Y', N'微信同步程序里面报告上传是否按照医院设置上传报告如果是true，那么判断exam_info表is_report_upload字段为1的上传')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_SAMPLE_STATUS', N'N', N'Y', N'打印条码是否直接采样')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_SAMPLING_DEL', N'Y', N'Y', N'已采样的是否可弃项（回收导引单处）')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_SEND_APPLICATION', N'N', N'Y', N'是否登记发送申请    Y表示登记时再发')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_SFZBD_UPDATECUSTOM', N'Y', N'Y', N' 身份证报道修改人员信息与身份证一致')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_SFZBD_UPDATEPIC', N'Y', N'Y', N' 身份证报道修改照片')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_SHOW_DAOJIANDAN_SHENGQINGDAN', N'N', N'Y', N'登记台是否展示打导检单申请单')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_SHOW_DELETE_ITEM', N'N', N'Y', N'已经停用的项目是否需要显示在页面： Y是 N否')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXX', N'IS_SHOW_HH_PAY', N'Y', N'Y', N'登记台团体加项 是否显示混合付费 Y显示 N不显示')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_SHOW_INVOICE_PAGE', N'N', N'Y', N'收费处是否默认勾选打印发票复选框')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_SHOW_PAIDUIHAO', N'N', N'Y', N'登记台是否展示打排队号')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_SHOW_REFVALUE', N'N', N'Y', N'总检结论检验科是否汇总参考值')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_SHOW_SAMPLENAME', N'N', N'Y', N'总检结论影像科是否以样本名称汇总')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_SHOW_SELECT_SHENQINGDAN', N'N', N'Y', N'登记台是否展示选择打申请单')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_SHOW_SHENQINGDAN', N'N', N'Y', N'登记台是否展示打申请单')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_SINGLE_REFUND', N'Y', N'Y', N'是否单项退费')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_SPECIALIST_SUGGEST', N'N', N'Y', N'是否需要录入专科建议（一般科室检查）')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_START_CARD_READER', N'Y', N'Y', N'是否启用读卡器')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_SYSLOG_PATH', N'D:\\hjw_syslog', N'Y', N'系统日志文件备份路径')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXX', N'IS_TBAODAO_QUEUE_SEND', N'Y', N'Y', N'团检报道是否发送排队申请')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_TCUSTOM_GH', N'N', N'Y', N'登记台团体新增和修改人员时是否做挂号操作')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXX', N'IS_TEAM_AMOUNT_VIEW', N'N', N'Y', N'控制团体金额、折扣率等是否可见的资源RS039是否生效')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_TGCUSTOM_GH', N'N', N'Y', N'登记台团体里个人付费时是否做挂号操作')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_TOLL_HTML', N'N', N'Y', N'登记台添加收费项目页面是否启用收费功能')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_VIEW_EXAM_IMAGE_SHOW', N'N', N'Y', N'影像科室是否显示缩略图')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_VIP_AMOUNT', N'1800', N'Y', N'vip人员最低消费额')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_WEBREPORTEXAMURL', N'Y', N'Y', N'微信同步程序里面可以web页面访问报告，Y表示判断页面请求来源')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_XIYUAN_EXAMINFO', N'N', N'Y', N'报到给平台发送身份信息  Y发送  N不发送')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_XIYUAN_EXAMINFOZHUCE', N'N', N'Y', N'团体界面发送申请')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'IS_XIYUAN_IDNUM', N'N', N'Y', N'登记台登记人员、团体备单身份证: Y可以为空  N不能为空')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'ISREADSTATUS', N'http://huojianwa.51vip.biz/sendExamResult.action', N'Y', N'上传报告地址')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'PACS_DEVICEID', N'5', N'Y', N'PACS设备id')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'REPORT_PATH', N'E:\报告打印4.2\hjw_Standard.exe', N'Y', N'预览报告 地址配置')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'REPORT_URL', N'E:\报告打印4.2\hjw_Standard.exe', N'y', N'报告预览执行程序目录')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'SEARCH_NUM', N'EXAM_NUM', N'Y', N'ARCH_NUM,EXAM_NUM 登记台页面配置根据体检号查询，还是根据档案号查询')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'SFZ_CARD', N'd009', N'Y', N'对应diver_info表设备编号')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'TEAM_ACCOUNT_ADD_ITEMIDS', N'', N'Y', N'团体结算附加费用项目id配置，以逗号隔开')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXX', N'TEAM_DJD_NAME_QUERY', N'N', N'Y', N'等级台按名字N模糊查询，Y精确查询')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'TEAMACCOUNT_URL', N'D:\\teamaccountServices\\TeamAccount.exe', N'Y', N'团体结算执行程序目录')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'xxxx', N'UPLOAD_FLOW', N'Y', N'Y', N'导检单回收上传流程, Y:表示在回收页面可以接上传')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'USER_INVOICE_NUM_LENGTH', N'10', N'Y', N'发票号段限制长度值,不维护就不限制')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'VIP_CUST_TYPE', N'6', N'Y', N'设置人员类型为vip')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'WEB_URL', N'', N'Y', N'webservice地址')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'WEIXIN_IS_CUSTOMER_TYPPE', N'N', N'Y', N'微信上传体检报告是否判断体检类型')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'WEIXIN_IS_CUSTOMER_TYPPE_ID', N'N', N'Y', N'微信上传体检报告是否判断人员类型')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'WEIXIN_IS_CUSTOMER_TYPPE_ID_IDS', N'1,5', N'Y', N'微信上传体检报告的人员类型')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'WEIXIN_IS_CUSTOMER_TYPPE_IDS', N'41,313', N'Y', N'微信上传体检报告的体检类型')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'xxxxxx', N'WXQZJ_URL', N'http://192.168.0.0:8080', N'Y', N'微信前置机ip端口，示例：http://192.168.0.0:8080')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'XYYY_01_FTPPORT', N'', N'Y', N'超声数据库ftp端口号')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'XYYY_01_FTPURL', N'', N'Y', N'超声数据库ftpurl')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'XYYY_01_URL', N'', N'Y', N'超声数据库url')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'XYYY_04_FTPPORT', N'', N'Y', N'心电数据库ftp端口号')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'XYYY_04_FTPURL', N'', N'Y', N'心电数据库ftpurl')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'XYYY_04_URL', N'', N'Y', N'心电数据库url')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'XYYY_05_FTPPORT', N'', N'Y', N'内镜数据库ftp端口号')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'XYYY_05_FTPURL', N'', N'Y', N'内镜数据库ftpurl')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'XYYY_05_URL', N'', N'Y', N'内镜数据库url')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'XYYY_06_FTPPORT', N'', N'Y', N'核医学数据库ftp端口号')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'XYYY_06_FTPURL', N'', N'Y', N'核医学数据库ftpurl')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'XYYY_06_URL', N'', N'Y', N'核医学数据库url')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'YB_DIAG', N'0', N'Y', N'医保诊断')
INSERT [dbo].[center_configuration] ([center_name], [config_key], [config_value], [is_active], [common]) VALUES (N'XXXXXX', N'YB_DOCTOR', N'0', N'Y', N'医保医师')
update center_configuration set config_value='Y' where config_key='IS_HIS_UNRELATED_SHOW' 