IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[web_version]') AND type in (N'U'))
DROP TABLE [dbo].[web_version]
go
CREATE TABLE [dbo].[web_version](
	[version] [varchar](7) NOT NULL,
	[seqid] [int] IDENTITY(1,1) NOT NULL,
	[createtime] [datetime] NOT NULL,
	[notices] [varchar](200) NULL,
 CONSTRAINT [PK_web_version] PRIMARY KEY CLUSTERED 
(
	[version] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'�汾��' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'web_version', @level2type=N'COLUMN',@level2name=N'version'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'˳���' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'web_version', @level2type=N'COLUMN',@level2name=N'seqid'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'����' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'web_version', @level2type=N'COLUMN',@level2name=N'createtime'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'˵��' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'web_version', @level2type=N'COLUMN',@level2name=N'notices'
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[web_version_list]') AND type in (N'U'))
DROP TABLE [dbo].[web_version_list]
go

CREATE TABLE [dbo].[web_version_list](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[version] [varchar](7) NOT NULL,
	[createtime] [datetime] NOT NULL,
	[notices] [varchar](2000) NOT NULL,
 CONSTRAINT [PK_web_version_list] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'�汾��' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'web_version_list', @level2type=N'COLUMN',@level2name=N'version'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'�����������' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'web_version_list', @level2type=N'COLUMN',@level2name=N'createtime'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'��������' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'web_version_list', @level2type=N'COLUMN',@level2name=N'notices'
GO


delete from web_version
delete from web_version_list

insert web_version(version,createtime,notices)values('2.0.1.0','2017-05-08','')
insert web_version_list(version,createtime,notices)values('2.0.1.0','2017-05-08','�����˽����طù����� �����ӱ� crm_member_private_doctor --˽��ҽ����crm_visit_plan �����ƻ���crm_visit_record �طü�¼��')
insert web_version_list(version,createtime,notices)values('2.0.1.0','2017-05-08','�����˺���ȫ��������ֹ��սṦ��     �����ӱ�team_account_trjn')
insert web_version_list(version,createtime,notices)values('2.0.1.0','2017-05-08','�ʾ�������� dep_homepage_show �ֶ� �Ƿ��ڼ��ҳ����ʾ')
insert web_version_list(version,createtime,notices)values('2.0.1.0','2017-05-08','�ܼ���۽�������������� IS_SHOW_REFVALUE -- �ܼ���ۼ�����Ƿ���ܲο�ֵ IS_SHOW_SAMPLENAME -- �ܼ����Ӱ����Ƿ����������ƻ���')
insert web_version_list(version,createtime,notices)values('2.0.1.0','2017-05-08','��ͨ���Ҽ����¼�뱣��bug�޸ģ���������ո񱣴棿���⣡��,�������� IS_DEPRESULT_SHOW -- ���ҽ���Ĭ����ʾ��')


insert web_version(version,createtime,notices)values('2.0.1.1','2017-05-09','')
insert web_version_list(version,createtime,notices)values('2.0.1.1','2017-05-09','����������������� �Ƿ����������Ŀ ���߼�')
insert web_version_list(version,createtime,notices)values('2.0.1.1','2017-05-09','���嵼��ʱ�򣬶Գ������ڽ����˴���')
insert web_version_list(version,createtime,notices)values('2.0.1.1','2017-05-09','���� �������������ʾ��ҳ������')
insert web_version_list(version,createtime,notices)values('2.0.1.1','2017-05-09','�ܼ��Ҹ����ҽ���б����Ӽ��ʱ����ʾ')
insert web_version_list(version,createtime,notices)values('2.0.1.1','2017-05-09','��Ա������bug')
insert web_version_list(version,createtime,notices)values('2.0.1.1','2017-05-09','�޸Ļ�Ա��BUG')
insert web_version_list(version,createtime,notices)values('2.0.1.1','2017-05-09','������ҳ��Ӽ��ʱ�����������Ӱ���������ʾ��Ŀ')
insert web_version_list(version,createtime,notices)values('2.0.1.1','2017-05-09','��ʵ���ƿ����Ѻ�δд��charging_way_single��bug')
insert web_version_list(version,createtime,notices)values('2.0.1.1','2017-05-09','���׼�¼����ѯ���������ѡ���ֵ��¼��ֻ�ܲ�ѯ�����ϼ�¼��')
insert web_version_list(version,createtime,notices)values('2.0.1.1','2017-05-09','�����Ѻ󣬿������δ������bug')


insert web_version(version,createtime,notices)values('2.0.2.0','2017-05-18','')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-18','���ӽɷ���Ŀ����')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-18','������쿨����ͽⶳ����')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-18','�ܼ���������')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-18','���Ӽ��������ֶ��빦��')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-18','�������ֵ�ά�� ��Ӧ data_code = ZJJBFL')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-18','�����˷����ѡ��Ա���͵Ĺ���')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-18','ÿ������߹���������¼�����ڲ�ѯ��������')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-18','�ܼ���������޸�')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-18','��ͨ�������Ӿܼ찴��')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-18','�޸��� ���û������η�������������Ŀ��ʱ�򣬽����ʾNaN�Ĵ���')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-18','�����������Ŀ���ڵǼ�̨���ܼӴֵ�����')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-18','�޸��˵�����Աʱ���������Ϊ���ڵĸ�ʽ��������������')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-19','��������ҡ��շ���Ŀ�������Ŀ��ϵά��')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-19','�°漲���߼������������֣�')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-19','�ܼ�ƥ������ҵļ����߼������ð���������򰴼�����������')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-19','��������ҳ����״̬������')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-19','�շѴ����˷ѡ��ײ͵���Ŀ��������ʾ')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-24','�ѽ��㡢���˵�����߿��Լ��������')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-24','�ܼ������������ IS_EXAM_SUMARRY_EDIT')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-24','�ܼ켲�������������� IS_EXAM_DISEASE_ITEM')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-24','�շѴ�����ۿ���Դ����')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-24','���������մ���ɨ��ǹɨһ���Զ�����һ����')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-24','�޸��˵Ǽ�̨������ӡ��bug')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-24','�������㽭��Ժ���֤����������')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-24','�޸��˸��Ʒ����bug')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-24','�����ƻ���bug�޸��ˣ�')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-26','�ܼ���۱������ֶ�-�ϴ�����ʱʹ��')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-26','�����߼�ά�������⣨��������С�ڣ�����ֵ������ֵ���ܼ�ҳ���̨����BUG��')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-26','ȥ���˷��鱻ʹ���Ժ󣬶������޸��շ���Ŀ�Ĺ��ܣ��ĳɷ��鱻ʹ���Ժ�����޸ķ�����շ���Ŀ')
insert web_version_list(version,createtime,notices)values('2.0.2.0','2017-05-26','�޸��˷���ʱ ����Ŀ�����ϸ���ظ�ʱ����������Ŀ�Ĺ���')


insert web_version(version,createtime,notices)values('2.0.2.1','2017-06-02','')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-02','�ܼ����ܼ�����޸�����ΪY�����޸�BUG,����ƽ��������Ե�ȥ���ˣ��쳣�����ֵ���ʾ')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-02','�շѴ��������� IS_CHARGINGWAY_ZERO -- �շѴ�ѡ�е��շѷ�ʽ���Ϊ0ʱ,���շѷ�ʽ�Ƿ�д�����ݿ�')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-02','��ͨ���Ҽ��������<br>��bug�޸�,Ӱ������¼���޸�2������¼��ͬһ���˵���Ŀ,��������2�����ݵ�����.')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-02','������������շ���Ŀȡ���ǼǵĹ��ܡ�')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-05','�������ܼ��б������ֶ�sql���')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-05','�Ǽ�̨�޸��� ���˲�����ʾ�ײ����Ƶ�bug')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-05','�Ǽ�̨��ȥ�Ժ󣬷���lis��pacs���뷵�ش����bug')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-09','�޸������η������水���ܽ�����������������bug')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-09','������嵼����ʽ���ʱ��������Ͳ���ƥ�������')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-09','�Ǽ�̨����������ϸ��Ϣ����˱����ʼķ�ʽ�Ĺ��ܣ�����������ݿ�report_receive�� receive_date�ֶο���Ϊ�գ�')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-09','����17�緽����ʾ�������˲���ҳ�����ʾ')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-09','����˵Ǽ�̨��ҳ����exel����')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-09','�޸��˽ɷ�0Ԫ��bug')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-12','�����˵Ǽ�̨��������ı�����ȡ��ʽ')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-12','�����˻�Ա���˷�')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-12','�ܼ���ʾ��ͨ����ר�ƽ���')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-12','�޸��˵Ǽ�̨����İ�����ʾ��bug')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-12','�޸��˵Ǽ�̨�����޸���Ϣ�Ĵ���')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-12','������ҳ�����˱���Ԥ�����ܣ�')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-12','�����˶������ʶ�����Ա����Ϊvip��Ȼ���pacs����vip��־<br>�������ʸ��°汾��Ҫ�� no-appCtx-jobDetail.xml �ļ��޸�ΪappCtx-jobDetail.xml������ҽԺ�����޸ġ�')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-14','���������������������Ľ��')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-14','�ռ�ҳ������һ������ѡ�������Ա����������')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-14','�ռ���Ա��ʾҳ���޸���Ա���������ʾ�����ص��ע��Ⱥ')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-18','�޸��˵Ǽ�̨ż������������ͬ�������Ϣ��bug')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-18','�޸���������㣬��ҳ��ʾ����������')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-18','�޸����ܼ������������Է��ֵ���������۲�')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-18','�޸��˿��������ظ����Է��ֵ���������۲�')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-18','�ܼ��ҵ����Է������������������������ʵ�����ڹ�˾���ԣ���ȷ�Ƚ���������Ӧ��4-9��֮�䡣�Գ������߼����˸��٣�Ŀǰ��ʱ�޸��õķ����Ż���')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-19','�������ʼı��湦��BUG')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-19','�ܼ����ܼ���ۻ�����ʽ�������ã��㽭��Ժ����')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-19','�޸�2017-06-18�Ǽ�̨���������������bug')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-19','��������ƣ����鱻ʹ���ˣ��Ͳ����޸ģ���Ϊ����޸ģ�ϵͳ����ںܴ��©����')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-19','������㣬������������Ȼ��������ѯ��ֱ�ӽ���Ĺ���')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-19','�޸��˽����sql����bug')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-20','�ܼ������ҽ����ʽ�ο�ֵ����')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-20','�ܼ콨�鲻�ܱ༭BUG')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-20','��ͨ���Ҽ��ѡ����Ŀ�������������Ӧ����λ�õ���')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-20','�޸�����Ǽ�̨������ʾ�����Ա�ķ����bug')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-20','������crm����������Ĳ�ʹ��crm�汾�����Բ�ִ�� crm_xtgnb.sql sql���')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-20','�ܼ���ۻ�����������')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-30','�ܼ�ϲ�����������������')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-30','�����������������ʾBUG')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-30','��Ա����vip��Աǰ����죬������������ʾ��ע����ɫ��Դ���ƾ���Ϊ��Щ�û���ʾ��vip��Ա���ͱ������ΪLXVIP')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-06-30','�������Ϊ����Ա��ְ��죬��ͨ����ȫ�ƻ���ƽ̨���ء�ע������Ա��ְ������ݱ������ΪTJLXRZTJ')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-03','��������������������Ŀ���ã�����ҳ����ʾ��Ŀ���ƺͽ��')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-03','�������������շ���Ŀ���ã���δ����Ŀ�б���ɫ��ʾ������ǰ��ע���������յ���������������ĸ��Ի����󣬱����Ŀ��Ҫִ�нű������ǲ���������ĿID')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-03','�ܼ����ܼ�����ʾ��Ϣȥ����Ա������Ϣ')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-04','�ܼ�������������ʽ����������������Ź���')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-04','���������޸ġ�ע��ԭ����ȷ�ϴ�ӡ���ӡ״̬���ã������¼ӱ��������ֶΣ������ӡ����ı���.')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-05','���������屸��ҳ�棬�����˵��쵥�Ƿ��ӡ״̬��ѯ')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-05','������Ա����ʱ�����֤�Ա�͵���ʱ��д���Ա𲻷�����������õ�����޶�')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-05','��������ʱ��ͨ���Ա𡢻������Ĺؼ����ж��Ա�ͻ��')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-05','�޸������������Ա��ʾ��������bug��')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-14','��ͨ��������ר�ƽ��鹦��')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-14','��ͨ��Ӱ�񡢼���������Ƭ��ʾ')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-14','�������ݷ�������')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-14','�ܼ�ϲ����Է���bug')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-14','�ܼ����Է��ֺͽ���༭����Ӧ�߶�')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-14','Ӱ��������������Ƿ���ʾ����ͼ����')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-14','�������޸��б���ʾ��Ϣ���������ݵ�������')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-14','�������������ά�����ܺ��ܼ���¼�������������')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-14','�������ҳ�����������������ʾ')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-14','���嵼�����������Ż�')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-14','ȥ���Ǽ�̨����������Ĭ��ѡ��Ĺ���')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-14','��λά����������ҵ���͡���ҵ���͵���Ϣ')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-14','��������ҵ����ҵ���������ֵ�ά������')
insert web_version_list(version,createtime,notices)values('2.0.2.1','2017-07-14','�����˵Ǽ�ҳ��ļ��±�����')


insert web_version(version,createtime,notices)values('2.1.1.0','2017-07-19','')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-19','�����˽���֤���ϴ����ܶ�������ʹ��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-19','�ܼ�ҳ���������Ƿ�ǩ������֤�Ĺ���')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-19','���ײ�������շ���Ŀ���������ϴ���־')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-19','�ӿ�������ɽ�������lis�Խӹ���')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-19','�����Ŀ��ϸ��������lis��Ӧ�Ĳ�������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-20','�ܼ�����Զ��������������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-21','���ӿ���ͬ����־')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-21','�ܼ��ֹ�������챨��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-21','������չ��λ')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-21','�ܼ���������ʽ�޸ĺ�����������Ű�ť�����޸�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-21','�ܼ�����б��޸���ʽ�����Ժ������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-21','�ܼ�ҳ�����Է����б����������������Ƿ��Զ��������Է�������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-21','�ܼ��ҳ��ʾ����')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-21','�ܼ���ҳ�����ܼ챣������ʾ')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-21','��ͨ���������Ա�����������Ӧ�����������ʾ�Ĺ��ܣ������ã�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-21','�ܼ����Է����б�༭���ݵ������޸ĺͿ��Ե����޸�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-21','�Ǽ�̨�������ݰ�����󵼳�����')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-26','����-�ܼ���ҳ��Ϣ�б����ӵ��ֻ�����ʾ')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-26','�ȼ�����-���շѴ����ӷ���ԭʼ�������ʾ')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-26','�ȼ�����-��Ա���б��մ���ʱ����������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-07-26','�Ǽ�̨������ӡҳ��״̬�޸���ʾΪ���Ѳ�����δ������ԭ��д�����ѷ��ͺ�δ����')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-08-09','�����˵����ϲ�����')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-08-09','�޸����ܼ��bug')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-08-09','Ӱ�������ͼƬ���ӣ��������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-08-09','�շѴ�����ӡ��Ʊ��ǰ��Ҫ�ܹ�Ĭ�Ϲ�ѡ')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-08-09','�����ӿڣ�ʵ��ɽ������ҽԺlis�Խӹ���')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-08-14','�޸ĵ����ϲ�bug')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-08-14','���շ���Ŀ���ײ͡����š������Ŀ��ɾ�ĵ�ʱ��д��־���������������ͬ��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-08-14','�ֹ�ɾ��exam_set\charging_item\department_dep������synchro��synchrodate�����ֶ�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-08-21','�շ�ʱ���ӱ�������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-08-21','��ҽ��Ժ�쵼����ܼ�ҳ�����������Ա�谴�������������������������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-08-21','�㽭��Ժ���Ǽ�̨���ӽ����ʾ�������ܡ�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-08-21','�㽭��Ժ���ӽ����ʾ��ײͺ��շ���Ŀ�ش����ܡ�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-08-21','��ҳ���Ӱ汾����ʾ')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-08-21','��ҳ����汾�ſɻ�ȡ�����޸���־��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-08-29','����������ӽ���֤�š�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-08-29','�շѴ��˷��޸����Ѵ����Ѿ��޸ĳɲ��ı��޸Ĵ���')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-08-29','�޸�bug���Ǽ�̨���������Ա�޸ģ���λ���Ʋ����治��ʾ�����⡣')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-01','�Ǽ�̨��ҳ�����屸����ҳ����˱��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-01','�޸�������Ǽ�ͳ��������ʾ��������bug')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-01','����������ȫ�µĴ�ӡģʽ��ͬʱ�����ϵĴ�ӡģʽ��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-01','�ռ�����Ա������/���˼�������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-01','�ռ�����Ա�б����ӱ�����ȡ��ʽ�У��ʼĴ�����ʾ')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-01','�ռ�����Ա�б������м����ģ��ú�ɫ��ʾ���С�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-01','��󱨸���������Ա������������ˢ��ҳ�����ԭҳ������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-01','�޸������֤���������bug')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-01','�ײ�ͣ��\���ù��ܣ�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-01','�ײ����˳�����ֶΣ��ײͱ༭ҳ���շ���Ŀ����')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-01','�Ǽ�̨��ҳ������Ա�����б�����˳���룡')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-01','�ײ͡��շ���Ŀ����˳��������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-01','���ײͺ��շ���Ŀ����ҳ�棬��ʾ�б�ʱ�򣬰��ײͱ�ź��շ���Ŀ���Ҳ�ֱ���ʾ����')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-06','������������ѯͳ��ҳ�棻')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-06','�շѴ������Ƿ����ñ������ܣ�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-06','���������޸ĺϲ�������ɾ�������ϢBUG��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-06','���չ��������ʼ���ȡ����ʱ���������������ȡ���ʼ���ȡ���湦�ܣ�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-06','������������dkq-A16D���֤��������ȡ���֤���ܣ�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-06','�����˻�Ա�����ۿۺ͵�λ��Ϣ��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-06','��Աɾ���ָ�ģ���б���ʾ��ӵǼ��ˡ��Ǽ�ʱ�䡢�޸��ˡ��޸����ڡ������Ա������������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-06','�Ǽ�̨�������Ա������������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-06','�޸��˵Ǽ�̨�������������������ͬ���շ���Ŀ���ͣ����������ʱ����ʾ��bug��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-06','������㣬��������ѡ����Աʱ��������һ�������жϣ��������ɷ���Ŀ����0����Ա�ű���ѯ������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-08','�޸��˵Ǽ�̨�Ĳ�ѯ�������ṩ�ٶ�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-08','�������ʱ��ȥ����������ĸ��˽���������ѯ')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-08','��������������״̬��ʾ��������͵���')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-08','�޸������ڼ��������bug')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-08','���ɾ���ͻظ��Ż��˲�ѯ����')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-08','��쵵������������ҳ����ʾ���')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-12','��������ѯͳ�������Է���Ա�Ľ���')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-12','�ܼ���Ӱ������б���������������ק������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-12','�ܼ����������Բ�����ҳ�棬ֱ���������б�����һ��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-15','�ܼ�����ҳ���������˰�ť')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-15','����ƽ��¼��ҳ�����Ӽ��ҽ�������ҽ����ѡ��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-15','��ͨ���ҽ��¼������ָ��û���Զ����ݲο�ֵ�ж��쳣��BUG�޸�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-15','���ӿ��Ҵ�ӡ���빦��ҳ�棨ֻ֧����ͨ���Һ�Ӱ����ҵ���Ŀ��ӡ�����Ҵ�ӡ��ťֻ֧���µ������ӡ����')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-15','����Ӱ����ҽ��������Թ���')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-18','Ӱ��������Ա�ǹ��ܵ���')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-18','�Ǽ�̨��ӡ���뱨��bug')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-18','����/����Ǽ�̨ҳ��:��ӡ���쵥���밴ť����ԤԼ��Ա�ı�������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-18','�����¼�������ҽ�������������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-18','�Ǽ�̨��ҳ���ӵ�λ��ʾ���ܣ������汾�����˹��ź��ײ�������ʾ������ҳ���ܵ�����λ�����š��ײ����ơ�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-18','�Ǽ�̨���˺�����Ǽ�ҳ�棬�޸���Ϣʱ�򣬲��ܱ���ͼƬ���޸��˴�bug��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-25','�޸�����������bug')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-25','����ʱ�������˰��������Աƽ������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-25','�޸��˱�����ʵ�ַ�������jdbc��hibernate��Ϸ�ʽ�޸ĳɴ�jdbc��ʽ')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-28','�ܼ�����ҳ�������ò�ѯ����Ĭ��ѡ������1�����������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-28','���ξ���ҳ���������ϸʵ����������������������ӿɰ���ʱ��μ���')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-28','������ȷ��������������ݣ�����ǿ�ƺϲ��������ܣ����Ӵ�ӡ������Դ����')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-28','����������Ӹ��ӷ���ά������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-28','��ͨ���������ַ�����BUG����ͨ����С�����������Ƿ���Ա༭')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-28','��Ա��������OCX�޸�Ϊ�����õ�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-29','�������ʽ���֤��ѡ�ɽ���֤�Ź��ܡ�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-09-29','�����Ա�����������밴ť����BUG��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-11','�㽭��Ժ������Ԥ����ֶ�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-11','��������Ա����ʱ���Ƿ����Ҫ���֤������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-11','�������㽭��Ժ�����Ż�ȡ�ĳ�����룬�Լ��ݺ����㱱����ҽԺ')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-17','�����Ա����ҳ���ѯ�������״̬�ɶ�ѡ���������ܵ����Ż���')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-17','��Ʊ��¼���������д���������ID��д��,д���ֶ�barchid��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-17','���ξ���ҳ�������Ա�б����ӵ�ַ����������ʾ��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-17','�Ǽ�̨ҳ�����ӽ�����ά�����ܡ�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-20','�Ǽ�̨��ҳ����ԤԼ���ڲ�ѯ�������Ǽ�̨��ҳ�б����ӽ�������ʾ')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-20','ȡ��������ʾ��Ϣ�޸�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-20','Ӱ���������ȫ�ƻ���ƽ̨����ʷ����Աȹ���')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-20','������㸽�ӷ���ά��ҳ���ѯȡ������������Ŀ��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-20','�ܼ�����ʷ����Աȵ���ҳ��Ϊ˫����Ԫ�񵯳�������ȡ���Զ��رչ��ܣ����ֶ��رյ���ҳ��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-20','������Ա����֧���Զ��嵵���ţ��Զ��嵵���Ų��ܺ�ϵͳ���������ɹ�����ͬ�������Զ��嵵���Ų����ԡ�TJ����ͷ���������ͷϵͳ���Զ������ºţ��;��￨�ŵ��빦�ܡ�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-20','����Ǽ�̨���ܼ컹�ܼ���BUG��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-20','����Ǽ�̨��ҳ���֤�������ܴ򵼼쵥����BUG��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-20','����������������ȡ�������ⱨ��ϵͳΨһ��ʾż��Ϊ��bug')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-20','��Է������ƽ̨���������Ϣ')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-20','������Ч��Ʊ��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-20','�����Ǽ�̨������ȡ��ʽд��examinfo��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-20','���ڴ������ݿո񣬱༭ʱ��ʾ����')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-20','�����ײ��ۿ۽��͵Ǽ�̨�ײͽ��Բ���bug')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-20','�Ǽ�̨��Ӿ��￨ά��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-20','�����������ſ����Զ���')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-20','�Ǽ�̨ɾ��������ʱ����his����')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-20','��������ԷҽԺ�Ľӿڰ�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-20','�Ǽ�̨��ҳ��������������ʾ1000��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-27','���Ӹ��˼������Ŀ���ܡ�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-27','����ײ������ײ����͵�ά�����ܡ�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-27','���������������ӽ������ֶε��롣')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-27','�շѴ����Ӵ�ӡ��ͨ�շѵ����ܡ�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-27','�޸�LIS����������Ŀ�ظ�BUG��')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-28','�Ǽ�̨������Ŀ��ʱ�򣬼���Ƿ��ظ�')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-28','���屸�����֤����������������ʾ���������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-28','��������б��մ������ڵ�������')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-28','������������Ա��ѯ�б�֧�ֲ��Ŷ�ѡ����')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-28','���������Ա�б�֧����ʾ����')
insert web_version_list(version,createtime,notices)values('2.1.1.0','2017-10-28','�޸��˵Ǽ�̨���˸���ҳ�治����ʾ�շ���Ŀ��Ŀ��bug')


insert web_version(version,createtime,notices)values('2.1.1.1','2017-11-09','')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-09','�����շ�Ա�սṦ�ܣ���������͸��ˣ�')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-09','���Ӳ������սṦ��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-09','����֤������ѡ��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-09','�շ���Ŀ���Ӳ������ά������')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-09','�����շ�����ʵʱ��ѯ����')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-09','��Ʊ�Ŷ�����ά������ҳ�棬֧�ֹ��÷�Ʊ�����˷�Ʊ����Ʊ����ѡ��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-09','��ͨ���ҽ��¼��������������Ŀ�����ܣ�ʵ�ַ�ʽ�����Ŀ�������ֵ����Сֵ�ֶΣ�')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-09','��������ԤԼ����')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-09','���������Ȳ�ѯҳ��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-09','��Ʊ�������ӷ�Ʊ���ϱ����ݲ��롢�ż���˵�������д����ȷ���տ��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-09','�շѴ��շ������Ƿ����������Ŀ')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-09','�޸����嵼��ʱ������ִ���ֹͣ��������⡣')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-09','���η���ʱ�������˸�����ͳ�ƹ���')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-14','���������Ӳ���������ܣ�')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-14','�����Ա�������������ϲ���������')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-14','�շ�Ա�������ս�ҳ�����ӷ�Ʊ������')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-14','�����½Ṧ��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-14','���������ѯҳ��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-14','δ��������Ŀ��ѯ�������빦��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-14','������Ŀ��ϵά��������������ӡ����ά��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-14','�Ǽ�̨���Ӵ�ӡ�˷ѵ�����')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-16','�շ���Ŀ���ƴ������շ���Ŀ��������Ŀ���Ա༭˳����')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-16','�Ǽ�̨������η���ά����������������Ŀ����')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-16','���ӿ��Ҳ�������')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-16','�����Ŀ�����Ա�ά������ͨ�����ֶι��˼����Ŀ�Ա�')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-16','�ܼ��������Է������������Ƿ񵯳�ҳ��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-16','��Ŀ���֪ʶ��ά���������ĿĬ��ֵ�������¼��ҳ���Զ�����Ĭ�Ͻ��������ѡ����ҽ���Ĳ����Ƿ���������')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-16','���֤��дX����¼��BUG')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-16','�Ǽ�̨��Ŀԭ��̫�ߣ����۵Ͳ��ܱ���BUG')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-16','ԤԼ���ڲ���ʹ��BUG')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-16','���ξ���ҳ�����Ӹ���������ݵ�������')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-21','�޸��˼���ʱ���жϽɷ�״̬��bug��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-21','�޸��˽ɷ�ʱ���жϽɷ�״̬��bug��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-21','�޸�����Ա����ʱ���bug��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-21','��������Ա����ʱ�����Ե���excel��ʽ�Ĵ�����Ա��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-21','�����������Զ�����ɹ��Ժ��ͳ�Ƴɹ�/δ�ɹ���������ʵ��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-21','�޸��˷���ʱ�򲻼����Ŀ�Ա��bug��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-21','�Ǽ�̨��ϸ��ʾҳ��������һ����ˢ�¡���Ŀ�İ�ť��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-21','�޸������ξ���ģ��ѡ����ʱ��ѯ�������ݵ�bug��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-21','������㣬����������Ͳ�ѯ��������λ��������͡����״̬������Ϊ�ɶ�ѡ��ʽ�������������ܡ��ɵ������ź�������͡�')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-24','��Ʊ�Ŷι̶�λ�����ƣ�λ��������')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-24','��ͨ���ҵ����Ѽ죬δ����������')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-24','�˷Ѵ�����Ʊ��ʾ����')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-24','����������Աʱ�򣬵����Ų����ڵ�����£��Զ���������')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-24','�Ǽ�̨����ʱ�������ã������ˣ�����������Ӽ���Ĺ���')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-24','��Ʊ�������˱���������ʵ��ŵĹ���')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-24','����������Ա�����ﱨ�������ҺŹ��ܡ�')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-27','�޸�������㣬��ԭ���İ��������Ϣ�����ɰ����������Ŀ����')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-27','���ӿ��԰����Ѽ����Ŀ����Ĺ���')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-27','�������Ժ󣬵Ǽ�̨�����ٴμ�������Ŀ��Ȼ���ٴ�����������ӵ������Ŀ����')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-11-27','�޸�����Ա����ʱ����������bug')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-12-01','�ѵǼǹ��������֤���ܼ����Ǽǵ�BUG')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-12-01','����������졢ɥż���ѻ�δ�����ѻ���������')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-12-01','�Ǽ�̨�Ա�Ĭ��ΪŮ')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-12-01','���յ��쵥�����ж��������ΪNULLʱ���Զ�д�����ʱ�䣬�޸ļ��״̬��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-12-01','���������֤�������Ƿ������Ƭ��������Ϣ������')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-12-06','������Ա����󣬿�ɾ��������Ϣ�İ�ť��')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-12-06','��������ά����Ĭ��Ϊ����')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-12-06','�޸����������ʱ����ú�����bug')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-01-18','��ͨ�������Ӹ�ѡ��ѡ������ָ����ʽ�޸�')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-01-18','���Ӳ����սᣬ�½ᵼ������')
insert web_version_list(version,createtime,notices)values('2.1.1.1','2017-01-18','�����ܼ첵�ع���')


insert web_version(version,createtime,notices)values('2.2.0.0','2018-06-22','')


insert web_version(version,createtime,notices)values('2.2.0.1','2018-07-02','')
insert web_version_list(version,createtime,notices)values('2.2.0.1','2018-07-02','�������ã��ڼ���Ŀʱ���ѯ�����ĳ�����ҵ��շ���Ŀ��һ���������˺Ĳ�����Ŀ��')
insert web_version_list(version,createtime,notices)values('2.2.0.1','2018-07-02','�ܼ�ҳ����ӹ���������������ʾ��ȫ��')
insert web_version_list(version,createtime,notices)values('2.2.0.1','2018-07-02','�������豸��')
insert web_version_list(version,createtime,notices)values('2.2.0.1','2018-07-02','������4.0���쵥��ر���')
insert web_version_list(version,createtime,notices)values('2.2.0.1','2018-07-02','�ܼ�������δ������Է��֣���ʾĬ�����Է�������')
insert web_version_list(version,createtime,notices)values('2.2.0.1','2018-07-02','���ӱ�������뱨���ƽ�����ҳ��')
insert web_version_list(version,createtime,notices)values('2.2.0.1','2018-07-02','�����Ա���������������ʾ���ˡ�����ɷѽ�������ҳ���������ҽ�����')
insert web_version_list(version,createtime,notices)values('2.2.0.1','2018-07-02','������Ա����ȥ��������ĵ������Ӻ��޸������Ϣ���ܣ�ͳһ��������Ǽ�̨���Ӻ��޸�')
insert web_version_list(version,createtime,notices)values('2.2.0.1','2018-07-02','�Ǽ�̨��ҳ������ҳ�棬���ӹ�������������ʾ��ȫ')
insert web_version_list(version,createtime,notices)values('2.2.0.1','2018-07-02','������Ա����ҳ����������β�ѯ')
insert web_version_list(version,createtime,notices)values('2.2.0.1','2018-07-02','����λ�޸����Ժ󣬸���exam_info������ĵ�λ����')
insert web_version_list(version,createtime,notices)values('2.2.0.1','2018-07-02','������Ŀҳ�棬�ڱ�ѡ����Ŀ�����Ĭ��5����¼')
insert web_version_list(version,createtime,notices)values('2.2.0.1','2018-07-02','�����˵ǼǺ�������˵ǼǴ�����ҳ�棬������ȡ���������ŵ���״̬�����沢���ȡ��������ʱ�������ʾһ����ʾ���Ƿ�ȡ�����������ȷ�����ȡ������')
insert web_version_list(version,createtime,notices)values('2.2.0.1','2018-07-02','����͸��˵Ǽ�̨ҳ������˴�ӡ�ĳ���bug')
insert web_version_list(version,createtime,notices)values('2.2.0.1','2018-07-02','�����˻��ڿ������νṹ���շ���Ŀά�����棬Ҫʹ�ô˹�����Ҫ��ʼ���˵�ѡ���շ���Ŀ����̨����')
insert web_version_list(version,createtime,notices)values('2.2.0.1','2018-07-02','�Լ����Ŀ���������������š������Ŀ������԰��ղ���ά����')


insert web_version(version,createtime,notices)values('2.2.0.2','2018-07-02','')
insert web_version_list(version,createtime,notices)values('2.2.0.2','2018-07-02','������Դ���ã��ڵǼ�̨������������ϴ��ܼ�δ���ʱ�Ƿ������ٴ�������')
insert web_version_list(version,createtime,notices)values('2.2.0.2','2018-07-02','���ÿ�������ҳ��������ʽ:1,����2,���')
insert web_version_list(version,createtime,notices)values('2.2.0.2','2018-07-02','�������ã��շ���Ŀ�۸�䶯ʱ�Ƿ������޸��ײͼ۸�')
insert web_version_list(version,createtime,notices)values('2.2.0.2','2018-07-02','�Ǽ�̨��ʾ�ڼ�����죬���һ���������')
insert web_version_list(version,createtime,notices)values('2.2.0.2','2018-07-02','�����շ���Ŀ����his�ķ�ʽ���ɹ���������Ŀ��۱�')
insert web_version_list(version,createtime,notices)values('2.2.0.2','2018-07-02','��������Ǽ�̨ͬʱ��ӡ���쵥�������4.0����')
insert web_version_list(version,createtime,notices)values('2.2.0.2','2018-07-02','�޸���ie�¸��˺�����Ǽ�ҳ��ͬʱ��ӡ���쵥�������4.0����')
insert web_version_list(version,createtime,notices)values('2.2.0.2','2018-07-30','������������ҳ������������Ĳ���')
insert web_version_list(version,createtime,notices)values('2.2.0.2','2018-07-30','�Ǽ�̨���˼���ҳ��ɰ��ս����д���')
insert web_version_list(version,createtime,notices)values('2.2.0.2','2018-07-30','�����ϸҳ�����ӿ����ֶΡ������տ������ι���')
insert web_version_list(version,createtime,notices)values('2.2.0.2','2018-07-30','�շ���Ŀ����ҳ�棬���տ������ι���')
insert web_version_list(version,createtime,notices)values('2.2.0.2','2018-07-30','���������屸������̨')
insert web_version_list(version,createtime,notices)values('2.2.0.2','2018-07-30','������������ʾ���ˡ�����ɷѽ��')
insert web_version_list(version,createtime,notices)values('2.2.0.2','2018-07-30','���Ӱ汾���Ʊ��Ժ����еİ汾�����޸���־ͳһ�ӿ��Ʊ��ȡ')


insert web_version(version,createtime,notices)values('2.2.0.3','2018-08-09','')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-09','�շ���Ŀ�������Ŀ�������������ҹ���ȥ��ɾ�����޸�Ϊͣ�û�����')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-09','�շ���Ŀ������Ŀ��ϵ�����������ֶ�')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-09','�޸������Ա��Ϣ��������')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-09','�����������ά����������ҳ�棬�����Ŀ��ʱ��������ͻس�ȥѡ����Ŀ')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-09','�޸ļ����Ŀ����ҳ�治���ύ�����⡣')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-09','�������180���ݵĳ�ʼ�����ݿ�')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-09','�޸Ŀ���¼��ʱ���ұ�Ŵ��ŵ�����')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-13','����֪ʶ��������ӿ�����')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-13','���������������Ŀ����ҳ��')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-13','�޸ĵǼ�̨�������ݴ���')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-13','�޸ģ����˵Ǽ�/����Ǽǣ��ĲĿ����޸�����������Ϊ0���ǺĲ�ֻ��Ϊ1')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-15','����֪ʶ�ⰴ�շ���������ʽ��ʾ')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-15','�����������ӷ��࣬������Ҫ�������ֵ�ά����YBFL��')



insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-21','���屸������̨ ���嵼�����ݻ���')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-21','��Ŀ������������/ͣ�ô���')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-21','�շ���Ŀ����ҳ�����ͣ�����ð�ť')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-21','�޸��շ���Ŀ�������ϸ���ѯ����')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-21','�����շ���Ŀ����ϸ��ҳ�����ɾ���Զ����湦��')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-21','���������շѹ���ҳ�������Ŀ����')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-21','�޸���������������ۿۺ� ����۸񲻻�ı�')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-21','�޸ĸ��˼����������ۿۺ�������')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-21','�޸����屸������̨ ��������ҳ�� �Ѽ���Ŀ����15��ʾ������')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-21','��������Ǽ� ���쵥���롢��������ʾ�Էѽ��')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-21','���ӵǼ�̨ ���֤������ʾ�Էѽ����ŷѽ��')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-21','�������ǼǸ���/�������ҳ�����ѡ���˸�����Ŀ')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-21','��������ʾ����5���ߡ�6���͵�״̬')

insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-23','�޸��ܼ����֮����̫��')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-23','����ܼ�ҳ���ܼ�ʱ�䣬���ʱ�䣬����Ϊ��ϸʱ��')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-23','�޸��ܼ�ҳ�棬���ҽ���ͼ��ʱ��ŵ������')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-23','�޸��쳣ָ����������ʾ����������������ʾ���ݣ���λ���ο�ֵ�ֿ�')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-23','��ӻ��յ���������������д�ʼķ�ʽ�ĵط�')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-23','��ӻ��յ��������������Ƿ��Զ����յ�����')

insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-27','��ӻ��յ���������������д�ʼķ�ʽ�ĵط�')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-27','��ӻ��յ��������������Ƿ��Զ����յ�����')

insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-28','�Ǽ�̨��Ӳ����Ǽǹ���')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-29','���ҹ���:���п��ҵ��Ѽ���Ա��Ϊ ȫ����Ŀ�Ѽ����Ա��û��ȫ�������ɵ�Ϊδ��')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-29','���п������:����Ϊ����״̬ ȫ����Ա��ȫ���Ѽ졢�����Ѽ졢δ����Ա')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-29','��Ա��:����Ϣ�޸ĵ�ʱ����Ҫ�޸ĵ�λ�����ڿ��Ļ�������')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-29','�ܼ�:�ܼ�������� null����Ŀ ��λ ��û����ʱ �ܼ�����ﵥλ��λ����ʾnull')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-29','�ܼ�:�ܼ�ҳ���˳�����һ�£�δ����Ŀ�� �ŵ� ���״̬����')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-29','���������-���⡱�Ӳ�ѯ����������Ϣ��ʾ�����顢�ײ͡���Ա����������')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-29','������ͨ���Ҽ����߼�ֻ�ܳ���һ��������')

insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-30','���ҽ�����Ϣ��ѯͬһ���˵���Ϣ����������bug����ѯ���������Ѽ��ܲ��ȫ���Ѽ�鲻������bug')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-30','���ҽ�����Ϣ��Ϣ��������ʾ��ɫ��ɫ��bug')

insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-31','�����ܼ������ʽ')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-31','�޸�ѡ����Ҳ�ѯ֮�󣬵������ ���ҷ���Ĭ��Ϊ���Ҳ�ѯ��')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-31','�޸��ż����� �鿴�رհ�ťʧЧ')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-31','�޸ĵ����ƿ������뱣������')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-31','�޸�ʵ���ƵĿ���Ϣ����޸ı���')
insert web_version_list(version,createtime,notices)values('2.2.0.3','2018-08-31','���쵥����ҳ�����Ӳ�������ѡ������Ŀ�Ĺ���')

insert web_version(version,createtime,notices)values('2.2.0.4','2018-09-12','')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-05','���������Ǽ�ҳ������ӡ���쵥�����쵥�����ʱ����ʾ����˵���Ա���ֻ��������ҳ��')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-05','�Ǽ�̨��ӭʹ��ҳ����ӵ�λ�ķ�����Ϣ')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-05','����ҳ����ӵ�λ��Ϣ')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-05','�޸��շ���Ŀ������������')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-05','�޸��շ���Ŀ���� ϸ���޸ĳ���')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-05','����Ƿ��ܼ����þͿɲ����Ǽ�')

insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-05','�޸Ķ���ʱ ���ܴ�ӡ����͵��쵥')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-05','�޸Ĵ�ӡ���쵥����ʾ�ٴδ�ӡ����Ϣ')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-05','��������Ǽ�ҳ�棬����򵼼쵥��ť����ʾ�Ѵ�ӡ����Ϣ')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-05','���쵥����ҳ�����Ӳ����ǼǺ��޸Ĳ����Ǽǣ���Դ��������� �����Ǽ�SQL��')


insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-07','�޸�����ǩ���ƻ�ҳ�� �ų�ײ����ҪȨ����Դ���䣨��Դ�������:�ų�ײ��Ȩ����ԴSQL��')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-07','�����������ά��ҳ�棺�޸�����������ͨ���޷�����')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-07','�޸�������� ��λ����ά�������ϼ���λ����Զ��������ظ���')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-07','�Ǽ�̨��ӭʹ��ҳ����Ա��Ϣ���ڷ�����ײ�֮����Ӳ�����Ϣ')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-07','�Ǽ�̨��ӭʹ��ҳ�棬���״̬���ǼǶ����޸ĳ��ѱ���')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-12','�Ǽ�̨�����屸������̨����Ա���롢������Ա������ӣ��Ļ��̶�(degreeOfedu)��������ò(data_dictionary)')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-12','����˵���״��ʾ')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-12','�޸���3��û�ر����ӵ�')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-17','�Ǽ�̨�������һ��ɾ��')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-12','disease_knowloedge_lib ��examination_item ��dept_id�����ĳɲ���t�ģ��ĺ�Ϊ��dep_id')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-12','�޸ķ����ʱ��ʹ��update�ķ���')

insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-14','�Ǽ�̨ҳ������ܼ�ʱ����ʾ ���԰����ܼ�ʱ������ ���԰������״̬����')

insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-17','180�����̹����й������طù�����Ų��2.0')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-26','�������̨ѡ����������ͬʱ��ѯֻ�ܲ�ѯһ����bug')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-26','������Ӱ��Ա�����İ�ť')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-26','��ֲ180�Ǽ�̨�����μ���ܵ�')

insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-30','�޸ļ���֪ʶ�����༭ʱ ���Ҵ����bug')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-30','�޸��շ���Ŀϸ��ҳ�� ��Ӱ�ť�������һ��')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-30','�շ���Ŀҳ���������ϸ��İ�ť')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-30','�շ���Ŀ����ҳ�� ����ͳ�ƿ��������')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-09-30','��������༭��Ϊ��ʱ ��������ҲΪ��')

insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-10-10','��ֲ180���̿���')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-10-10','��ֲ180�����ܼ칦��')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-10-10','��ֲ180Σ��ֵ����ģʽ')

insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-10-12','���ӳ��ǹ���-��Դ����������ۿ��ʵ��Ƿ�ɼ�')

insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-10-12','��Դ�����ڵǼ�̨��ҳ�Ƿ�ͨ����ť�����շ�ҳ��')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-10-12','������һ�������� ���֤�Ż򵵰���ֻ����һ�����')

insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-10-14','��Դ�����Ƿ������һ���Ѿ�ʹ�õķ�������޸�')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-10-14','�����ڵǼ�̨��λ��Ա��������ģ�����߾�ȷ��ѯ')

insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-10-16','���ÿ��԰�����Դ������ʾ��λ��Ϣ')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-10-16','�޸�������㣬ȥ�����������')
insert web_version_list(version,createtime,notices)values('2.2.0.4','2018-10-16','�޸�����ͷ���գ�ȡ����ռʽ��ʽ')

insert web_version(version,createtime,notices)values('2.2.0.5','2018-10-18','')
insert web_version_list(version,createtime,notices)values('2.2.0.5','2018-10-18','���ӵ���������Ǽ���Ա����Ŀ��ʽ��������Ŀ����ۿۡ��������������Ŀ�����ҳ�� ��center_configuration����DJT_ADD_TIEM_TYPE����Ϊ3')
insert web_version_list(version,createtime,notices)values('2.2.0.5','2018-10-18','�շ���Ŀ�������ֶΣ�����շ���Ŀ�ۿ���SQL��')
insert web_version_list(version,createtime,notices)values('2.2.0.5','2018-10-18','�ײͼ���Ŀ�ۿ�Ҳ�����޸� ��������ڵ��ڹ涨�ۿ۽��')
insert web_version_list(version,createtime,notices)values('2.2.0.5','2018-10-18','���˼���ҳ�� ��������ۿ۽�����ƣ��Լ���������ۿ�����')
insert web_version_list(version,createtime,notices)values('2.2.0.5','2018-10-18','������˼���ҳ�� ��������ۿ۽�����ƣ���������ۿ�')
insert web_version_list(version,createtime,notices)values('2.2.0.5','2018-10-18','������˼��������ײ�ʱ��������ۿ�����')

insert web_version_list(version,createtime,notices)values('2.2.0.5','2018-10-18','����������� ��������ۿ۽�����ƣ���������ۿ�')
insert web_version_list(version,createtime,notices)values('2.2.0.5','2018-10-18','����������� �����ײ�ʱ��������ۿ�����')
insert web_version_list(version,createtime,notices)values('2.2.0.5','2018-10-18','�������������ֶ� ������������������������SQL��')
insert web_version_list(version,createtime,notices)values('2.2.0.5','2018-10-18','����������������������������  ')
insert web_version_list(version,createtime,notices)values('2.2.0.5','2018-10-18','�������ҳ����Ȩ�޿��� �Ƿ�������center_configuration��������IS_HAVE_MAX_AMOUNT�������������Ƿ������������SQL��')
insert web_version_list(version,createtime,notices)values('2.2.0.5','2018-10-18','����ײ͹���ҳ�� �޸��ۿ۽��Ӧ�������۽��')
insert web_version_list(version,createtime,notices)values('2.2.0.5','2018-10-18','����ײ͹���ҳ��  ��ͨ�������ۿ���')
insert web_version_list(version,createtime,notices)values('2.2.0.5','2018-10-18','����ײ͹�������������Żݽ������ ')
insert web_version_list(version,createtime,notices)values('2.2.0.5','2018-10-18','�����޸���Ŀʱ�����û�ѡ���Ƿ�һ���޸�ԤԼ��Ա�Ѿ�������Ŀ')
insert web_version_list(version,createtime,notices)values('2.2.0.5','2018-10-18','�Ǽ�̨��ҳ������Աģʽ���������Ե�����ǰ��ѯ�����������ݣ������ǵ�ǰҳ��')
insert web_version_list(version,createtime,notices)values('2.2.0.5','2018-10-18','�Ǽ�̨�����Ҽ�顢�ܼ��ҳbug����')
insert web_version_list(version,createtime,notices)values('2.2.0.5','2018-10-18','�Ǽ�̨�����Ҽ�顢�ܼ�����ɫ��ע')

insert web_version(version,createtime,notices)values('2.2.0.6','2018-10-28','')
insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-28','bug �޸ģ�����ҳ�泬��15�����ݲ���ʾ�����ӹ�����')
insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-28','�����ʼı���ʱ��')
insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-28','����ײ��У��Ѽ���Ŀ�������')
insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-28','�ܼ�ҳ�� ��ʾ��Ϣ���У����տ�������')
insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-28','���һس� �ж��Ƿ����Ϊ�շ�״̬��ǰ���ѣ�')
insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-28','���һس� �Ƿ��иĸÿ��������Ŀ')
insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-28','�������Ŀ��ƵǼ�̨��ϸ��Ϣ�༭ҳ�水ť����ʾ ')

insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-28','�����Ժ�޸ģ����쵥���մ�����ϴ�������ֱ���ϴ�����')
insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-28','�����Ժ�޸ģ��������ϴ����߱��������� ��������״̬����')
insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-28','�����Ժ�޸ģ��������ظ����յ��쵥���Ӽ�¼')
insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-28','�����Ժ�޸ģ���ӡ��δ���Ҳ����ǿ�ƽ��գ���ӡ���ظ����յ��쵥���Ӽ�¼ ')
insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-28','�����Ժ�޸ģ����ӿ���Ϣ�������ۿ�������״̬')
insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-28','�����Ժ�޸ģ��������õǼ�̨��ӡ�����Ƿ��ж���Ŀ�Ƿ񸶷� ')


insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-31','��Ŀ���֪ʶ����� �������޸� ����ֶ� ��������������������������ֶ�SQL��')
insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-31','��λά���������ӵ�λ����ֶΣ����������˾����ֶ�SQL��')
insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-31','���Ǽ�̨�����˺�����Ǽ�ҳ���Tabҳ�棬�������Ϣ�������Ա����䡢���֤ �Ǳ������exam_ext_info��')
insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-31','��󱨸�����������Ų�ѯ���������Ӵ��С����ݵ��������� ')
insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-31','�Ǽ�̨���Ӳ��Ų�ѯ')
insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-31','������ͨ����С�ἲ���߼��� ')
insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-10-31','�ܼ��Ҽ����߼��ж����������Լ�ϵͳ���ܱ� ')

insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-11-01','��Ϳ��ҽ�����Ҫ�ܰ��ռ���ղ�ѯ������ʾ����')
insert web_version_list(version,createtime,notices)values('2.2.0.6','2018-11-01','��ͨ���ҽ��� ���ս���������ʽ���� ')


insert web_version(version,createtime,notices)values('2.2.0.7','2018-12-23','')
insert web_version_list(version,createtime,notices)values('2.2.0.7','2018-11-01','�Ǽ�̨�����Ƿ�Ĭ��Ϊ10�ۻ���ʵ�ʽ������ۿ� ')
insert web_version_list(version,createtime,notices)values('2.2.0.7','2018-11-12','������̳�������� ')
insert web_version_list(version,createtime,notices)values('2.2.0.7','2018-11-20','���κ�ƽ������Ŀ�����ۿ����� ')
insert web_version_list(version,createtime,notices)values('2.2.0.7','2018-11-20','����̫�࣬�޷���ʾȫ��������������ģ���������� ')
insert web_version_list(version,createtime,notices)values('2.2.0.7','2018-11-20','���Ҽ�飬δ����״̬����ɫ��ʾ')
insert web_version_list(version,createtime,notices)values('2.2.0.7','2018-11-20','��ȡ�����޸�ΪĬ��')

insert web_version_list(version,createtime,notices)values('2.2.0.7','2018-11-20','������ݽ��㵥����Ŀ�����Ϣ���������ۿۣ�')
insert web_version_list(version,createtime,notices)values('2.2.0.7','2018-12-04','���η��ʵ�ҵ�����̴���')
insert web_version_list(version,createtime,notices)values('2.2.0.7','2018-12-07','���Ӳ����Ҵ�ӡ�����Զ��������ܡ�')
insert web_version_list(version,createtime,notices)values('2.2.0.7','2018-12-07','�����շ�ҳ�棬ѡ�����շѷ�ʽ�Զ����������⡣')
insert web_version_list(version,createtime,notices)values('2.2.0.7','2018-12-07','�Ǽ�̨��ҳ Ĭ�Ϲ�ѡ��ѡ�� ���쵥�����롢������ͨ��cookieʵ�֡�Ĭ�Ϲ�ѡ�Բ���Ա���һ�εĹ�ѡΪ׼��')

insert web_version_list(version,createtime,notices)values('2.2.0.7','2018-12-04','��ͨ���ҡ�������ҡ���������ҳ������������Ͳ�ѯ')
insert web_version_list(version,createtime,notices)values('2.2.0.7','2018-12-07','������������ʾ�Ѽ��������δ���������������˴Ρ������˴�')
insert web_version_list(version,createtime,notices)values('2.2.0.7','2018-12-20','Σ��ֵҳ�����Ӳ�ѯ��������������Σ��ֵ')
insert web_version_list(version,createtime,notices)values('2.2.0.7','2018-12-20','������180�����̿��ƻ���')


insert web_version(version,createtime,notices)values('2.2.0.8','2019-02-27','')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-02-27','��������Ӱ����ҽ�����������ֶ�')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-02-27','���ӵ¿���Ա������')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-02-27','����Σ��ֵ��������')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-02-27','������ת������ת��')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-02-27','��ͨ�ܼ�ģʽ����ҳ�б���� �����ܼ�״̬��')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-02-27','�����屸������̨ҳ���������һ���������Ƿ�����ֶΣ������������޸İ�ť����ѡ���Ƿ���ˡ�')

insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-02-27','�޸��ܼ��ҿ���С���߼��뼲���߼����á�')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-02-27','180ģʽ�ܼ�ҳ������ά�������ƻ�����')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-02-27','180�ܼ�ģʽ��ֲһ��ȡ����ָ�����')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-02-27','���˵Ǽ�̨���շѴ����˷Ѵ���ҳ�����Ӳ�ѯ�շѼ�¼�Ĺ���')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-02-27','.�ۺϲ�ѯҳ������δ��������δ�ɡ�����δ�����棬������ֲ')

insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-02-27','�ܼ졢��ˡ����󡢿��Ҽ��ļ����ʷ��¼��ѯ�Ĺ�����ֲ')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-02-27','��Ժ��ͨ���Ҽ��ҳ���������޸Ľ��۲����Զ����ܽ��۵Ĺ��ܡ���ֻ���������ñ�� is_dept_typeΪERYUAN�����ã�')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-02-27','�Ǽ�̨��ʾ�ʾ�')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-02-27','��ҽ���������������ʷ�������ҽָ����ά��')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-02-27','�����ܼ��ڵ��쵥���մ��͵Ǽ�̨�޸�����ʾ')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-02-27','���Ӳ���ҳ�棬���ÿ����õ�������͵�����ʾ5����')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-02-27','������Ա�޸�ҳ�棬ȡ���˱��������������ƹ���')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-02-27','�޸�����Ա�޸���ʾ��Ϣ�������Ա�һ�µ�bug')


insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-03-06','Ӱ����ҽ���ʿ�����Ĭ��ֵ����')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-03-06','��Ŀ�Ѽ죬����¼��ҳ��¼���ߵ�Ĭ�Ϲ���')

insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-03-06','window.open���´��ڣ����֮ǰҳ��δ�ر���С�����ٴδ�ʹ���ҳ���ٴλ�ý���')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-03-06','���˵Ǽ�̨ѡ����Ա���ܴ����Ա��bug')
insert web_version_list(version,createtime,notices)values('2.2.0.8','2019-03-06','�Ǽ�̨�����շ�ҳ�棬��������Ա��Ϣ��bug')



insert web_version(version,createtime,notices)values('4.0.0.1','2019-06-5','')
