package com.hjw.wst.DTO;

/**
 * NFixcardId generated by MyEclipse - Hibernate Tools
 */

public class WebRoleDTO implements java.io.Serializable {
	 private static final long serialVersionUID = -97502163798576023L;
	// Fields
	private String id;

	private String rolename;

	private String remark;

	private String datetime;
	
	private String ry;
	
	private String selected;
	
	private String r_id;
	
	public String getR_id() {
		return r_id;
	}

	public void setR_id(String r_id) {
		this.r_id = r_id;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getRolename() {
		return rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getDatetime() {
		return datetime;
	}

	public void setDatetime(String datetime) {
		this.datetime = datetime;
	}

	public String getRy() {
		return ry;
	}

	public void setRy(String ry) {
		this.ry = ry;
	}

	public String getSelected() {
		return selected;
	}

	public void setSelected(String selected) {
		this.selected = selected;
	}

}